services:
  couchbase:
    image: couchbase:community
    container_name: couchbase
    ports:
      - 8091-8094:8091-8094
      - 11210:11210
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: couchbase-springboot-app
    depends_on:
      - couchbase
    ports:
      - 8080:8080